const nodemailer = require('nodemailer');
const admin = require('firebase-admin');

// Create reusable transporter object using SMTP transport
const transporter = nodemailer.createTransport({
  service: 'gmail',
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD
  }
});

const db = admin.firestore();

function cleanNewsletterContent(rawContent) {
  if (typeof rawContent !== 'string') return rawContent;
  // Remove triple backticks and optional 'json' after them
  let cleaned = rawContent.trim();
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json\s*/, '');
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```\s*/, '');
  }
  if (cleaned.endsWith('```')) {
    cleaned = cleaned.replace(/```\s*$/, '');
  }
  return cleaned;
}

function formatNewsletterContent(newsletter) {
  let content = newsletter.content;
  if (typeof content === 'string') {
    content = cleanNewsletterContent(content);
    try {
      content = JSON.parse(content);
    } catch (e) {
      // If not JSON, use as is
    }
  }

  if (content && Array.isArray(content.headings)) {
    let sectionsHtml = content.headings.map(
      h => `
        <section style="margin-bottom: 24px;">
          <h2 style="color: #2a2a2a; margin-bottom: 8px;">${h.heading}</h2>
          <p style="color: #444; font-size: 16px; line-height: 1.6; margin: 0;">${h.content}</p>
        </section>
      `
    ).join('');
    return `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; background: #fff; padding: 32px 24px; border-radius: 8px; box-shadow: 0 2px 8px #0001;">
        <h1 style="color: #1a73e8; font-size: 2em; margin-bottom: 8px;">${content.title || newsletter.title || 'Newsletter'}</h1>
        <div style="color: #888; font-size: 14px; margin-bottom: 24px;">${content.date ? `Date: ${content.date}` : ''}</div>
        ${sectionsHtml}
        <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
          <p style="color: #666; font-size: 12px;">
            This newsletter was automatically generated by Flacron Sports.<br/>
            To unsubscribe, please contact support.
          </p>
        </div>
      </div>
    `;
  }

  // Fallback: pretty print JSON as HTML
  let contentHtml = '';
  if (typeof content === 'object') {
    contentHtml = `<pre style="font-size:14px;">${JSON.stringify(content, null, 2)}</pre>`;
  } else {
    contentHtml = `<div>${content}</div>`;
  }
  return `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h1 style="color: #333;">${newsletter.title || 'Newsletter'}</h1>
      <div style="margin: 20px 0;">
        ${contentHtml}
      </div>
      <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee;">
        <p style="color: #666; font-size: 12px;">
          This newsletter was automatically generated by Flacron Sports.<br/>
          To unsubscribe, please contact support.
        </p>
      </div>
    </div>
  `;
}

// Function to send newsletter to users with newsletterEnabled
async function sendNewsletter() {
  try {
    // Fetch users from dashboard_settings with newsletterEnabled true
    const snapshot = await db.collection('dashboard_settings').get();
    const recipients = [];
    snapshot.forEach(doc => {
      const data = doc.data();
      if (data.newsletterEnabled) {
        recipients.push(doc.id);
      }
    });
    if (recipients.length === 0) {
      console.log('No users with newsletterEnabled found.');
      return;
    }

    // Fetch the latest newsletter from newsletters collection (order by date desc, limit 1)
    const newsletterSnap = await db.collection('newsletters')
      .orderBy('date', 'desc')
      .limit(1)
      .get();
    if (newsletterSnap.empty) {
      console.log('No newsletter found in newsletters collection.');
      return;
    }
    const newsletter = newsletterSnap.docs[0].data();

    // Format the newsletter content
    const formattedContent = formatNewsletterContent(newsletter);
    // Use the title from the parsed content if available
    let subject = newsletter.title;
    let parsedContent = newsletter.content;
    if (typeof parsedContent === 'string') {
      parsedContent = cleanNewsletterContent(parsedContent);
      try {
        parsedContent = JSON.parse(parsedContent);
      } catch (e) {}
    }
    if (parsedContent && parsedContent.title) {
      subject = parsedContent.title;
    }

    // Send email to each recipient
    const mailOptions = {
      from: process.env.EMAIL_USER,
      subject: subject || 'Flacron Sports Newsletter',
      html: formattedContent
    };

    console.log(`Sending newsletter to ${recipients.length} users...`);
    for (const email of recipients) {
      mailOptions.to = email;
      await transporter.sendMail(mailOptions);
      console.log(`Newsletter sent to ${email}`);
    }
    console.log('Newsletter distribution completed');
  } catch (error) {
    console.error('Error sending newsletter:', error);
    throw error;
  }
}

module.exports = {
  sendNewsletter
}; 